### ISSUE TITLE
Feature: make roc-schema.js show the full URI for each term in the markdown file it outputs

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/ro-crate-schema-tools#7]
Currently does not display - eg here: https://github.com/Language-Research-Technology/language-data-commons-vocabs/blob/master/ontology.md#annotationOf

Should look like:

# Property: annotationOf (http://w3id.org/ldac/terms#annotationOf)

This resource contains some kind of description that adds information to the resource it references.
Values expected to be one of these types:

[[ PrimaryMaterial ](https://github.com/Language-Research-Technology/language-data-commons-vocabs/blob/master/ontology.md#PrimaryMaterial)] |
Used on these types:
[[ http://schema.org/CreativeWork ](http://schema.org/CreativeWork)] |

**Comment by rosanna-smith** [comment]
Got it running on a test version:
Property: annotationOf (http://w3id.org/ldac/terms#annotationOf)

@ptsefton Do you need the same to be done for other sets like Defined Term and DefinedTermSets?

e.g.
Defined Term: WrittenLanguage
TThe resource contains data for which the medium of interaction was writing.

Is an expected value for the following property
[[ communicationMode ](https://purl.archive.org/language-data-commons/terms#communicationMode)] |

**Comment by ptsefton** [comment]
Yes for an definitions for all the terms plz

On 10 July 2024 12:43, Rosanna ***@***.***> wrote:

Got it running on a test version:
Property: annotationOf (http://w3id.org/ldac/terms#annotationOf)

Do you need the same to be done for other sets like Defined Term and DefinedTermSets?

e.g.
Defined Term: WrittenLanguage
TThe resource contains data for which the medium of interaction was writing.

Is an expected value for the following property
[ communicationMode <https://purl.archive.org/language-data-commons/terms#communicationMode> ] |

**Comment by rosanna-smith** [comment]
Having trouble adding you as a reviewer to the pull request so copying it here: https://github.com/Language-Research-Technology/ro-crate-schema-tools/pull/9

**Comment by rosanna-smith** [comment]
Maybe I don't have the right permissions in ro-crate-schema-tools

**Comment by rosanna-smith** [comment]
Ok to close this one @ptsefton or did we want to update [ontology.md](https://github.com/Language-Research-Technology/language-data-commons-vocabs/blob/master/ontology.md)? That's on a different repo so is there a good process for updating those files?

**Comment by ptsefton** [comment]
Yep - run `make ont` in https://github.com/Language-Research-Technology/language-data-commons-vocabs (assumes you have rocschema installed in your path)
