### ISSUE TITLE
Fix the help text in the commandline for rocsoss (it's a copy and paste from the roc-schema.js tool)

### ISSUE THREAD

**Issue by ptsefton** [Arkisto-Platform/ro-crate-schema-tools#8]
Should describe what rocsoss actually does, ie make schemas/modes from examples

**Comment by rosanna-smith** [comment]
Just to check, is this the description that should also be added to rocsoss?
Extracts a markdown or HTML page from an RO-Crate containing Schema.org style Classes and Properties.

**Comment by ptsefton** [comment]
I was confused - closing this issue as not needed
